"
I am a record for the 'Step to next instance creation' command in the Sindarin debugger.
"
Class {
	#name : 'DSSindarinStepToNextInstanceCreation',
	#superclass : 'DSAbstractSindarinActionRecord',
	#category : 'DebuggingSpy-Records',
	#package : 'DebuggingSpy',
	#tag : 'Records'
}

{ #category : 'accessing' }
DSSindarinStepToNextInstanceCreation >> eventName [

	^ 'Step to next instance creation'
]
