"
I'm a class with instance variables to test variable breakpoints events.
"
Class {
	#name : 'DSTestClassWithInstanceVariables',
	#superclass : 'Object',
	#instVars : [
		'a',
		'b',
		'c',
		'd'
	],
	#category : 'DebuggingSpy-Tests',
	#package : 'DebuggingSpy-Tests'
}

{ #category : 'accessing' }
DSTestClassWithInstanceVariables >> a [

	^ a
]

{ #category : 'accessing' }
DSTestClassWithInstanceVariables >> a: anObject [

	a := anObject
]

{ #category : 'accessing' }
DSTestClassWithInstanceVariables >> b [

	^ b
]

{ #category : 'accessing' }
DSTestClassWithInstanceVariables >> b: anObject [

	b := anObject
]

{ #category : 'accessing' }
DSTestClassWithInstanceVariables >> c [

	^ c
]

{ #category : 'accessing' }
DSTestClassWithInstanceVariables >> c: anObject [

	c := anObject
]

{ #category : 'accessing' }
DSTestClassWithInstanceVariables >> d [

	^ d
]

{ #category : 'accessing' }
DSTestClassWithInstanceVariables >> d: anObject [

	d := anObject
]
